server:
  port: 9091
spring:
  data:
    mongodb:
      host: localhost
      uri: mongodb://admin:12345@localhost:27017/userDB?authSource=userDB
      port: 27017
      username: admin
      password: 12345
      database: userDB
      